version: "3.9"

services:
  web:
    build: .
    container_name: badge42
    depends_on:
      - db
    restart: unless-stopped
    lebels:
      traefik.enable: true
      traefik.http.routers.badge42.entrypoints: https
      traefik.http.routers.badge42.rule: Host(`badge.nimon.fr`)
      traefik.http.routers.badge42.tls: true
      traefik.http.routers.badge42.tls.certresolver: letsencrypt
      traefik.http.services.badge42.loadbalancer.server.port: 3000
    networks:
      - default
      - traefik_traefik
    environment:
      DATABASE_URL: "postgres://YOUR_USER:YOUR_PASSWD@db:5432/badge42"
      NEXTAUTH_URL: "https://badge.nimon.fr"
      NEXTAUTH_SECRET: YOUR_RANDOM_SECRET
      FORTY_TWO_CLIENT_ID: YOUR_42API_CLIENT
      FORTY_TWO_CLIENT_SECRET: YOUR_42API_SECRET
    

  db:
    image: postgres
    restart: unless-stopped
    networks:
      - default
    volumes:
      - /media/data/mysql/badge42_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: "YOUR_USER"
      POSTGRES_PASSWORD: "YOUR_PASSWD"
      POSTGRES_DB: "badge42"

networks:
  default:
  traefik_traefik:
    external: true
